name: Build and push python code to gcp
on:
   push:
       branches: [main]
jobs:
        build_push_grc:
                name: Build and push to gcr
                runs_on: unbuntu-latest
                env: 
                        IMAGE_NAME: learning_cicd:latest

